# mysql2

default: &default
  adapter: mysql2
  host: localhost
  pool: 20
  encoding: utf8

development:
  <<: *default
  database: devise_omniauth_fb_development
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: devise_omniauth_fb_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
